### ISSUE TITLE
noop field is mutually overriden by providers

### ISSUE THREAD

**Issue by vdomah** [Flynsarmy/oc-sociallogin-plugin#1]
Hello!

here: https://github.com/Flynsarmy/oc-sociallogin-plugin/blob/master/socialloginproviders/Facebook.php#L67

noop field needs to be defined as 'providers[Facebook][noop]'. Same in all providers.

**Comment by Flynsarmy** [comment]
Why? It's not a value I want to save and send back to the db. It's just a partial containing html with no form fields.

**Comment by vdomah** [comment]
because only one noop partial is displaying at a time. E.x. you have Google, Twitter, Facebook tabs in settings page. And only on Google tab we see noop content displayed (/partials/backend/forms/settings/_google_info.htm). Other 2 tabs got no noop content, because 'noop' field is overriden by Google tab settings.

**Comment by Flynsarmy** [comment]
Fixed through https://github.com/Flynsarmy/oc-sociallogin-plugin/commit/d82665f0d1056c491fd0db671731c61eea7f875d
