### ISSUE TITLE
hybridauth update to 3.1

### ISSUE THREAD

**Issue by vdomah** [Flynsarmy/oc-sociallogin-plugin#2]
Can you please update the hybridauth package? I need Apple provider, which is present only from v3.1

**Comment by vdomah** [comment]
I removed plugin's vendor and done composer require hybridauth/hybridauth. It gets v3.7. So may be you need to specify version as 3.*?

**Comment by Flynsarmy** [comment]
Fixed through https://github.com/Flynsarmy/oc-sociallogin-plugin/commit/d82665f0d1056c491fd0db671731c61eea7f875d
