### ISSUE TITLE
Apple requires callback url to accept POST

### ISSUE THREAD

**Issue by vdomah** [Flynsarmy/oc-sociallogin-plugin#3]
Hello!
I got Apple working after changing this:
Route::get('flynsarmy/sociallogin/{provider}/callback'
to
Route::any('flynsarmy/sociallogin/{provider}/callback'

in routes.php

**Comment by Flynsarmy** [comment]
Nice one. If you send a PR with that change I'll approve it

**Comment by Flynsarmy** [comment]
Fixed through https://github.com/Flynsarmy/oc-sociallogin-plugin/commit/9e3b00f001897ba97f93ccf14bb3c9a536f02d43
